version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: cider-map
    volumes:
      - /srv/cider-map:/cider-map/map_grids
    ports:
      - "8000:8000"
    