version: '3'

services:
  db:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    container_name: cider-map
    volumes:
      - .:/cider-map
    ports:
      - "8420:8000"
    depends_on:
      - db
